# 필요한 모듈 설정

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib import patches
%matplotlib inline

# 데이터 로드

In [2]:
wine = pd.read_csv('WineQT.csv')
wine.drop(["Id"],axis=1, inplace=True) # 필요없는 'Id' column 제거
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

## 데이터 크기, 결측치 확인

In [3]:
wine.shape

(1143, 12)

In [4]:
wine.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

## 데이터 전처리 : good / bad

- 2 ~ 6.5 : bad
- 6.5 ~ 8 : good

In [5]:
my_bins = (2, 6.5, 8)
groups = ['bad', 'good']
wine['quality'] = pd.cut(wine['quality'], bins = my_bins, labels = groups)

# Modeling

## Scaled, Normalization

In [6]:
from sklearn import preprocessing
from imblearn.over_sampling import SMOTE 

oversample = SMOTE()
features, labels =  oversample.fit_resample(wine.drop(["quality"],axis=1), wine["quality"])
scaler = preprocessing.MinMaxScaler()
scaled_data = pd.DataFrame(scaler.fit_transform(features), columns=features.columns)
scaled_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0.247788,0.397260,0.000000,0.068493,0.106845,0.149254,0.098940,0.567548,0.606299,0.137725,0.153846
1,0.283186,0.520548,0.000000,0.116438,0.143573,0.358209,0.215548,0.494126,0.362205,0.209581,0.215385
2,0.283186,0.438356,0.040000,0.095890,0.133556,0.208955,0.169611,0.508811,0.409449,0.191617,0.215385
3,0.584071,0.109589,0.560000,0.068493,0.105175,0.238806,0.190813,0.582232,0.330709,0.149701,0.215385
4,0.247788,0.397260,0.000000,0.068493,0.106845,0.149254,0.098940,0.567548,0.606299,0.137725,0.153846
...,...,...,...,...,...,...,...,...,...,...,...
1963,0.498667,0.149887,0.481941,0.082458,0.067296,0.058543,0.010738,0.334380,0.356703,0.218823,0.562064
1964,0.646162,0.210652,0.657225,0.149343,0.160983,0.134328,0.059955,0.726199,0.320650,0.309520,0.306437
1965,0.230088,0.164384,0.460000,0.082192,0.103506,0.343284,0.134276,0.386931,0.519685,0.311377,0.400000
1966,0.388284,0.158777,0.431151,0.099936,0.074822,0.179104,0.074205,0.367114,0.435998,0.325579,0.654663
1967,0.377817,0.236914,0.521414,0.203928,0.142438,0.030766,0.014134,0.416104,0.372976,0.160095,0.573005

In [7]:
normalized_arr = preprocessing.normalize(scaled_data)
normalized_data = pd.DataFrame(normalized_arr, columns=features.columns)
normalized_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0.247821,0.397313,0.000000,0.068502,0.106859,0.149274,0.098953,0.567623,0.606380,0.137743,0.153867
1,0.279605,0.513966,0.000000,0.114966,0.141757,0.353679,0.212822,0.487878,0.357625,0.206931,0.212661
2,0.301354,0.466480,0.042566,0.102042,0.142124,0.222361,0.180493,0.541454,0.435718,0.203910,0.229203
3,0.513628,0.096372,0.492461,0.060232,0.092491,0.210005,0.167800,0.512011,0.290823,0.131646,0.189408
4,0.247821,0.397313,0.000000,0.068502,0.106859,0.149274,0.098953,0.567623,0.606380,0.137743,0.153867
...,...,...,...,...,...,...,...,...,...,...,...
1963,0.470961,0.141559,0.455164,0.077876,0.063557,0.055290,0.010141,0.315802,0.336884,0.206665,0.530835
1964,0.483831,0.157731,0.492115,0.111825,0.120540,0.100582,0.044893,0.543761,0.240095,0.231762,0.229453
1965,0.217253,0.155214,0.434339,0.077607,0.097732,0.324134,0.126785,0.365347,0.490695,0.294007,0.377687
1966,0.343939,0.140643,0.381910,0.088523,0.066277,0.158649,0.065730,0.325187,0.386203,0.288396,0.579896
1967,0.344900,0.216273,0.475986,0.186161,0.130028,0.028086,0.012903,0.379852,0.340481,0.146147,0.523082

In [8]:
from numpy import log
import warnings
warnings.filterwarnings(action='ignore')
unskew_data = normalized_data.copy(deep=True)

## Classifier Models

In [9]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn import metrics

In [10]:
rnd_clf = RandomForestClassifier()
log_clf = LogisticRegression()
dt_clf = DecisionTreeClassifier()
kn_clf = KNeighborsClassifier()
svm_clf = SVC()

models = [rnd_clf, dt_clf, kn_clf, svm_clf, log_clf]

## train / test split

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(unskew_data, labels, test_size=0.2, random_state=42)

## fit

In [12]:
for m in models:
    m.fit(X_train, y_train)

## predict

In [13]:
accuracy = []
precision = []
recall = []
F1 = []

for m in models:
    y_pred = m.predict(X_test)
    print(m.__class__.__name__,'Acc: ', accuracy_score(y_test,y_pred))
    print(m.__class__.__name__,'Precision: ', precision_score(y_test,y_pred, average = "macro"))
    print(m.__class__.__name__,'Recall: ', recall_score(y_test,y_pred, average = "macro"))
    print(m.__class__.__name__,'F1: ', f1_score(y_test,y_pred, average = "macro"))
    
    print("")
    
    acc = accuracy_score(y_test,y_pred)
    pcs = precision_score(y_test,y_pred, average = "macro")
    rec = recall_score(y_test,y_pred, average = "macro")
    f1 = f1_score(y_test,y_pred, average = "macro")
    
    accuracy.append(acc)
    precision.append(pcs)
    recall.append(rec)
    F1.append(f1)
    
    print("")

RandomForestClassifier Acc:  0.9670050761421319
RandomForestClassifier Precision:  0.9673453608247422
RandomForestClassifier Recall:  0.9676708018466458
RandomForestClassifier F1:  0.9670031631095106


DecisionTreeClassifier Acc:  0.9238578680203046
DecisionTreeClassifier Precision:  0.9243420204676102
DecisionTreeClassifier Recall:  0.9245609057849534
DecisionTreeClassifier F1:  0.9238559059987632


KNeighborsClassifier Acc:  0.916243654822335
KNeighborsClassifier Precision:  0.9206905503634475
KNeighborsClassifier Recall:  0.9179454775230186
KNeighborsClassifier F1:  0.9161783193114785


SVC Acc:  0.8959390862944162
SVC Precision:  0.8980303970223324
SVC Recall:  0.8971578160059835
SVC F1:  0.895922325092938


LogisticRegression Acc:  0.8350253807106599
LogisticRegression Precision:  0.8351113172541744
LogisticRegression Recall:  0.8354138188945917
LogisticRegression F1:  0.8349988080741699

# Metrics Score

In [14]:
metrics = [accuracy, precision, recall , F1]
total = []

for i in range(5):
    avg = 0
    for mt in metrics:
        avg += mt[i]*0.25
    total.append(avg)
        
print(total)

[0.9672561004807576, 0.9241541750679079, 0.9177645005050699, 0.8967624061039176, 0.835137331233399]